import os
import json

from datetime import datetime


class UnityProject:
    """
    Creates and manages a Unity project
    structure generated by Caine.
    """

    def __init__(
        self,
        name,
        location="unity_projects"
    ):

        self.name = (
            name.replace(" ", "_")
        )

        self.location = location

        self.path = os.path.join(
            location,
            self.name
        )


        self.folders = [

            "Assets",

            "Assets/Models",

            "Assets/Materials",

            "Assets/Animations",

            "Assets/Audio",

            "Assets/VFX",

            "Assets/Scripts",

            "Assets/Scenes",

            "Assets/Prefabs",

            "ProjectSettings",

            "CaineData"

        ]



    def create(self):

        os.makedirs(
            self.path,
            exist_ok=True
        )


        for folder in self.folders:

            os.makedirs(
                os.path.join(
                    self.path,
                    folder
                ),
                exist_ok=True
            )


        self.create_metadata()


        return self.path



    def create_metadata(self):

        metadata = {

            "project_name":
                self.name,

            "engine":
                "Unity",

            "version":
                "Unity 6",

            "created":
                datetime.utcnow()
                .isoformat(),

            "generated_by":
                "Caine"

        }


        file = os.path.join(
            self.path,
            "CaineData",
            "project.json"
        )


        with open(
            file,
            "w"
        ) as f:

            json.dump(
                metadata,
                f,
                indent=4
            )


        return metadata



    def get_folder(
        self,
        folder
    ):

        return os.path.join(
            self.path,
            folder
        )



    def save_state(
        self,
        data
    ):

        file = os.path.join(
            self.path,
            "CaineData",
            "world_state.json"
        )


        with open(
            file,
            "w"
        ) as f:

            json.dump(
                data,
                f,
                indent=4
            )



    def load_state(self):

        file = os.path.join(
            self.path,
            "CaineData",
            "world_state.json"
        )


        if not os.path.exists(file):

            return None


        with open(
            file,
            "r"
        ) as f:

            return json.load(f)