from dataclasses import dataclass, field
from datetime import datetime
from uuid import uuid4


@dataclass
class Command:
    """
    A single instruction generated by Caine.

    Commands are engine-independent.
    """

    command_type: str

    payload: dict

    priority: int = 5

    command_id: str = field(
        default_factory=lambda: str(uuid4())
    )

    created: str = field(
        default_factory=lambda:
        datetime.utcnow().isoformat()
    )

    status: str = "pending"

    def complete(self):

        self.status = "completed"

    def fail(self):

        self.status = "failed"

    def to_dict(self):

        return {

            "id": self.command_id,

            "type": self.command_type,

            "priority": self.priority,

            "status": self.status,

            "created": self.created,

            "payload": self.payload

        }